# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{doctorup}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["codesponge"]
  s.date = %q{2010-04-29}
  s.default_executable = %q{doctorup}
  s.description = %q{(BETA) If you use textile and want to to add syntax highlighting for code blocks then doctorup is for you!  Uses a simple DSL that makes writing documentation and turorials a snap! }
  s.email = %q{billy@codesponge.com}
  s.executables = ["doctorup"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/doctorup",
     "docs/converter.rb",
     "docs/doctorup.example.html",
     "docs/doctorup.example.textile",
     "docs/images/codesponge.png",
     "docs/snippet.example.html",
     "docs/snippet.example.textile",
     "doctorup.gemspec",
     "lib/codesponge.rb",
     "lib/doctorup.rb",
     "lib/snippet.rb",
     "test/data/article.erb.textile",
     "test/data/themes.erb.textile",
     "test/helper.rb",
     "test/test_codesponge_options.rb",
     "test/test_doctorup.rb",
     "test/test_snippet.rb",
     "test/test_ultraviolet_development.rb"
  ]
  s.homepage = %q{http://github.com/codesponge/doctorup}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{(BETA) syntax highlighting made easy}
  s.test_files = [
    "test/helper.rb",
     "test/test_codesponge_options.rb",
     "test/test_doctorup.rb",
     "test/test_snippet.rb",
     "test/test_ultraviolet_development.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<hpricot>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
  end
end

